name: civiclens-backend
region: nyc
services:
  - name: backend
    github:
      repo: Pratik-Shirodkar/CivicLens
      branch: main
      deploy_on_push: true
    source_dir: /backend
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3001
    run_command: npm start
    
